### ISSUE TITLE
wrong card displaying when strings are too long

### ISSUE THREAD

**Issue by sewera** [blazejsewera/notipie#35]
Analogous to [rr/issues/2](https://github.com/blazejsewera/reactive-raven/issues/2).

**Comment by sewera** [comment]
Possible solution:

```css
.txt {
  text-overflow: ellipsis;
  max-width: 100%; /* or some static value */
}
```

[stack overflow src](https://stackoverflow.com/questions/31928710/text-overflow-ellipsis-on-dynamic-width-element#31928777)
